sudo: required
services:
  - docker

before_install:
  - docker build -t escobard/docker-aws-product-ui -f ./ui/Dockerfile.dev ./ui
  - docker build -t escobard/docker-aws-product-api -f ./api/Dockerfile.dev ./api

scripts:
  - docker run escobard/docker-aws-product-ui npm run test -- --coverage
  - docker run escobard/docker-aws-product-api npm run test

after_success:
  - docker build -t escobard/docker-aws-product-ui-prod -f ./ui/Dockerfile.prod ./ui
  - docker build -t escobard/docker-aws-product-api-prod -f ./api/Dockerfile.prod ./api
  - docker build -t escobard/docker-aws-product-pgdb-prod -f ./pgdb/Dockerfile.dev ./pgdb
  - docker build -t escobard/docker-aws-product-nginx-prod -f ./nginx/Dockerfile.prod ./nginx