sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t escobard/docker-aws-product-ui-test -f ./client/ui/docker/Dockerfile.test ./client/ui
  - docker build -t escobard/docker-aws-product-api-test -f ./server/api/docker/Dockerfile.test ./server/api

scripts:
  - docker run escobard/docker-aws-product-ui-test || travis_terminate 1
  - docker run escobard/docker-aws-product-api-test || travis_terminate 1

after_success:
  # TODO - for GCP - ensure each image (coming from dockerhub) works out of the box for both GCP and AWS
  - docker build -t escobard/docker-aws-product-ui-prod -f ./client/ui/docker/Dockerfile.prod ./client/ui
  - docker build -t escobard/docker-aws-product-api-prod -f ./server/api/docker/Dockerfile.prod ./server/api
  - docker build -t escobard/docker-aws-product-nginx-prod -f ./nginx/Dockerfile.prod ./nginx
  # Login to Docker using a single command - this may not be working due to my PW's special characters, need may need to further debug
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push escobard/docker-aws-product-ui-prod
  - docker push escobard/docker-aws-product-api-prod
  - docker push escobard/docker-aws-product-nginx-prod

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-aws-product
  env: DockerAwsProduct-env
  bucket_name: elasticbeanstalk-us-east-2-689097371951
  bucket_path: docker-aws-product
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
