version: '3'
services:
  ## should leverage docker images instead of custom solutions where applicable
  ## more here: https://hub.docker.com/_/postgres
  postgres:
    image: 'postgres:latest'
  ## more here: https://hub.docker.com/_/redis
  redis:
    image: 'redis:latest'
  api:
    ## builds an image rather than grabbing it from dockerhub
    build:
      ## specifices the specific docker file
      dockerfile: Dockerfile.dev
      ## specifies the docker image root directory
      context: ./api
    volumes:
      ## tells docker compose to avoid creating a volume for this directory
      - /api/node_modules
      ## tells docker compose to create a volume for the api directory
      - ./api:/api
    ## env variables with docker-compose
    environment:
      ## uses the redis image specified above
      - REDIS_HOST=redis
      ## this is the default redis port
      - REDIS_PORT=6379
      ## more on default values: https://hub.docker.com/_/postgres
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./ui
    volumes:
      - /ui/node_modules
      - ./ui:/ui
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
    - /worker/node_modules
    - ./worker:/worker